### ISSUE TITLE
make an "ops-ish data" cheatsheet

### ISSUE THREAD

**Issue by cmharlow** [cmh2166/sdr_current_state#7]
i just need this for knowing where logs + monitoring are right now, bc our machines + application deployments are a mess.

**Comment by jmartin-sul** [comment]
some of this sort of info should be in DevOpsDocs, though DevOpsDocs is definitely incomplete.  but capturing this sort of "how do i figure out what went wrong?" info is one of the main goals of that repo:  https://github.com/sul-dlss/DevOpsDocs/

not comprehensive by any means, and definitely better filled out for newer projects, but a starting point, at least.

**Comment by cmharlow** [comment]
Thanks @jmartin-sul - i was actually using those + puppet docs to piece what i could together. Check out the spreadsheet embedded in #10 PR - https://docs.google.com/spreadsheets/d/1_2L2fxUccPImcjhbjIQEj2VPUy4hZNUthAEKfFGws20/edit#gid=0

if i can use this to get through what i need, i was hoping to then push into devopsdocs or quimby. 

does this look helpful or overkill?

**Comment by jmartin-sul** [comment]
ah, yeah, should've figured you'd already seen devopsdocs!  and yup, that spreadsheet seems helpful (i can't seem to access it anymore, but it looked very useful when i checked it out yesterday afternoon).  and pushing newly captured knowledge back into devopsdocs and/or quimby seems like a good plan.

**Comment by cmharlow** [comment]
lol, i got worried about security concerns legit bc of what i was collecting there. i need to share to the group explicitly i think.
